export const PROVINCES = [
    'Jujuy',
    'Salta',
    'Tucuman',
    'Chaco',
    'Formosa',
    'La Rioja',
    'San Juan',
    'Corrientes',
    'Santa Fe',
    'Catamarca',
    'Chubut',
    'Entre Ríos',
    'La Pampa',
    'Mendoza',
    'Buenos Aires',
    'Misiones',
    'Neuquén',
    'Rio Negro',
    'Tierra del fuego',
    'San Luis',
    'Santa Cruz',
    'Santiago del estero',
    'Córdoba'
].sort()
